services:
    open-webui:
        ports:
            - 3001:8080
        volumes:
            - /home/shady/ai/open-webui:/app/backend/data
        container_name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        restart: unless-stopped